[general]
live_config_reload = true
import = ["/home/joaooliveiradev/.config/alacritty/themes/poimandres.toml"]


[cursor]
style = "Beam"

[font]
size = 16


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
startup_mode = "windowed"

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 10
y = 10