[colors.bright]
black = "#a6accd"
blue = "#add7ff"
cyan = "#89ddff"
green = "#5de4c7"
magenta = "#fae4fc"
red = "#d0679d"
white = "#ffffff"
yellow = "#fffac2"

[colors.normal]
black = "#1b1e28"
blue = "#89ddff"
cyan = "#add7ff"
green = "#5de4c7"
magenta = "#fcc5e9"
red = "#d0679d"
white = "#ffffff"
yellow = "#fffac2"

[colors.primary]
background = "#1b1e28"
foreground = "#a6accd"