
[cursor]
style = "Beam"

[font]
size = 16

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.90

[window.dimensions]
# TODO: This resolution is good in Zorin OS but we need a good one for manjaro as well
columns = 120
lines = 30

[window.padding]
x = 15
y = 15

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/poimandres.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
